## Data Exploration of Parlamentary Data

In [10]:
# Written by Magnus Olander

from collections import defaultdict
from datetime import datetime
import json
import os

# Get parlamentary data from data directory
json_file_name = "../../data/data_all/data_all_final.json"

# Open file
with open(json_file_name, "r") as file:
    database = json.load(file)

#### How Many Questions/Answers Per Party

In [11]:
def questions_per_party(database):
    dict_ans = defaultdict(int)
    
    for entry in database:
        asked_by_party = entry["undertecknare_partibet"]

        dict_ans[asked_by_party] += 1

    # Print the counts for each key
    print("\nQuestions per party:")
    for key, count in dict_ans.items():
        print(f"{key} {count} times.")
        
def answers_per_party(database):
    dict_ans = defaultdict(int)
    
    for entry in database:
        answe_by_party = entry["besvaradav_partibet"]

        if answe_by_party != "":
            dict_ans[answe_by_party] += 1

    # Print the counts for each key
    print("\nAnswers per party:")
    for key, count in dict_ans.items():
        print(f"{key} {count} times.")

In [12]:
questions_per_party(database)
answers_per_party(database)

Questions per party:
MP 579 times.
S 4810 times.
FP 748 times.
V 1455 times.
M 6726 times.
KD 822 times.
C 771 times.
SD 2445 times.
- 44 times.
L 597 times.

Answers per party:
C 1396 times.
M 4206 times.
KD 922 times.
FP 693 times.
S 10092 times.
MP 1647 times.

#### Which Party Answered/Questioned Which Party

In [13]:
def party_asked_which_party(database):
    dict_ans = defaultdict(lambda: defaultdict(int))
    
    for entry in database:
        asked_by_party = entry["undertecknare_partibet"]
        answe_by_party = entry["besvaradav_partibet"]

        dict_ans[asked_by_party][answe_by_party] += 1

    # Print the counts for each key
    for key, key_counts in dict_ans.items():
        print(f"\n{key} questioned:")
        for value, count in key_counts.items():
            print(f"{value} {count} times.")




def party_answered_which_party(database):
    dict_ans = defaultdict(lambda: defaultdict(int))
    
    for entry in database:
        asked_by_party = entry["undertecknare_partibet"]
        answe_by_party = entry["besvaradav_partibet"]

        if answe_by_party != "":
            dict_ans[answe_by_party][asked_by_party] += 1

    # Print the counts for each key
    for key, key_counts in dict_ans.items():
        print(f"\n{key} answered:")
        for value, count in key_counts.items():
            print(f"{value} {count} times.")

In [14]:
party_asked_which_party(database)
party_answered_which_party(database)

MP questioned:
C 165 times.
M 228 times.
FP 64 times.
KD 52 times.
 13 times.
S 50 times.
MP 7 times.

S questioned:
M 2483 times.
C 791 times.
KD 534 times.
FP 439 times.
 21 times.
MP 115 times.
S 427 times.

FP questioned:
M 423 times.
KD 86 times.
C 84 times.
FP 41 times.
 2 times.
S 97 times.
MP 15 times.

V questioned:
M 542 times.
KD 99 times.
C 114 times.
FP 30 times.
 3 times.
S 561 times.
MP 106 times.

M questioned:
FP 55 times.
C 140 times.
M 194 times.
KD 87 times.
S 5407 times.
MP 843 times.

KD questioned:
M 199 times.
C 76 times.
KD 17 times.
FP 43 times.
 2 times.
MP 83 times.
S 402 times.

C questioned:
M 96 times.
KD 36 times.
FP 17 times.
C 26 times.
MP 94 times.
S 502 times.

SD questioned:
M 40 times.
FP 4 times.
KD 8 times.
S 2086 times.
MP 307 times.

- questioned:
KD 3 times.
M 1 times.
S 40 times.

L questioned:
S 520 times.
MP 77 times.

C answered:
MP 165 times.
S 791 times.
KD 76 times.
V 114 times.
FP 84 times.
M 140 times.
C 26 times.

M answered:
S 2483 times.
FP 423 times.
V 542 times.
KD 199 times.
C 96 times.
MP 228 times.
M 194 times.
SD 40 times.
- 1 times.

KD answered:
S 534 times.
FP 86 times.
V 99 times.
KD 17 times.
MP 52 times.
C 36 times.
M 87 times.
SD 8 times.
- 3 times.

FP answered:
S 439 times.
M 55 times.
MP 64 times.
V 30 times.
KD 43 times.
FP 41 times.
C 17 times.
SD 4 times.

S answered:
L 520 times.
M 5407 times.
V 561 times.
SD 2086 times.
KD 402 times.
S 427 times.
C 502 times.
MP 50 times.
- 40 times.
FP 97 times.

MP answered:
S 115 times.
KD 83 times.
SD 307 times.
M 843 times.
C 94 times.
L 77 times.
V 106 times.
MP 7 times.
FP 15 times.

#### How many Questions per Month/Year

In [15]:

def questions_per_month(database, years):

    # Init dicts to store the counts
    total_counts = defaultdict(int)
    monthly_counts = defaultdict(int)
    yearly_counts = defaultdict(lambda: defaultdict(int))

    # Iterate through database
    for entry in database:

        # Parse date to a datetime object
        date_object = datetime.strptime(entry["question_date"], "%Y-%m-%d")
        
        # Update total counts
        total_counts[date_object.month] += 1
        
        # Update monthly counts
        monthly_counts[date_object.strftime("%B")] += 1
        
        # Update yearly counts
        yearly_counts[date_object.year][date_object.strftime("%B")] += 1

    # Average for all months and years
    total_months = 12*years
    average_count = sum(total_counts.values()) / total_months

    # Print all results
    print("\nAverage Questions Per Month", average_count)

    print("\nAverage Questions For Each Month")
    for month, count in monthly_counts.items():
        print(f"{month}: {count/4}")

    print("\nQuestions Per Month")
    for year, counts in yearly_counts.items():
        print(f"Year {year}:")
        for month, count in counts.items():
            print(f"    {month}: {count}")

In [16]:
years = 16 #How many years back your data goes through

questions_per_month(database, years)

Average Questions Per Month 98.94270833333333

Average Questions For Each Month
May: 433.75
October: 387.0
April: 386.0
August: 248.5
July: 183.75
June: 484.0
December: 510.0
November: 460.5
March: 539.5
February: 488.25
January: 441.25
September: 186.75

Questions Per Month
Year 2010:
    May: 77
    April: 83
    August: 36
    July: 15
    June: 93
    March: 89
    February: 115
    January: 56
    October: 27
    November: 85
    December: 47
Year 2009:
    October: 102
    December: 103
    November: 92
    March: 107
    June: 75
    April: 67
    February: 110
    January: 85
    May: 32
    August: 68
    July: 62
Year 2008:
    December: 133
    November: 98
    October: 127
    February: 181
    March: 150
    April: 110
    January: 101
    June: 132
    August: 80
    July: 102
    May: 81
Year 2007:
    November: 156
    October: 124
    December: 159
    March: 200
    May: 162
    April: 117
    June: 168
    August: 95
    January: 126
    July: 43
    February: 112
Year 2006:
    November: 176
    October: 69
    December: 169
Year 2014:
    January: 98
    August: 19
    July: 21
    March: 70
    June: 81
    February: 56
    May: 32
    April: 29
    September: 1
    November: 62
    October: 26
    December: 28
Year 2013:
    December: 138
    September: 60
    October: 41
    November: 51
    July: 48
    August: 38
    June: 73
    May: 58
    April: 53
    March: 83
    February: 36
    January: 67
Year 2012:
    October: 62
    September: 49
    November: 101
    December: 23
    February: 57
    January: 76
    June: 55
    April: 60
    May: 53
    March: 77
    August: 10
    July: 15
Year 2011:
    October: 60
    September: 31
    November: 86
    December: 75
    February: 59
    January: 52
    June: 67
    March: 68
    May: 79
    August: 29
    July: 13
    April: 51
Year 2017:
    September: 90
    December: 170
    October: 108
    November: 128
    January: 148
    March: 189
    February: 86
    August: 92
    July: 62
    June: 194
    May: 190
    April: 116
Year 2018:
    June: 165
    May: 142
    January: 149
    March: 192
    February: 155
    July: 29
    April: 94
    September: 3
    August: 44
    November: 1
    October: 1
Year 2016:
    October: 172
    September: 83
    December: 193
    November: 129
    March: 175
    February: 103
    June: 89
    May: 161
    August: 88
    April: 119
    January: 125
    July: 49
Year 2015:
    October: 143
    September: 55
    December: 125
    November: 118
    April: 120
    March: 80
    February: 59
    January: 26
    May: 99
    August: 22
    July: 34
    June: 108
Year 2022:
    February: 155
    January: 180
    March: 156
    April: 76
    May: 112
    June: 113
    July: 39
    August: 51
    September: 8
Year 2021:
    October: 182
    December: 258
    September: 135
    November: 58
    August: 110
    June: 210
    January: 303
    February: 323
    July: 60
    April: 250
    March: 330
    May: 258
Year 2020:
    November: 365
    September: 157
    October: 145
    December: 260
    February: 131
    January: 106
    August: 138
    May: 144
    April: 127
    March: 109
    July: 126
    June: 197
Year 2019:
    November: 136
    September: 75
    October: 159
    December: 159
    March: 83
    January: 67
    July: 17
    June: 116
    August: 74
    May: 55
    February: 215
    April: 72